# Generated by Django 5.2.17 on 2026-09-20 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='expected_grade',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='grade',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='xrays/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='probabilities',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='symptoms',
            field=models.TextField(blank=True, default=''),
        ),
    ]
